Repository MIT-Emerging-Talent/ET6-CDSP-group-19-repo, pull requests merged in 2025-07, with the labels that each got.

#54 3 eda exploration
  2_data_preparation/README.md
  3_data_exploration/README.md
  3_data_exploration/notebooks/03_eda_juvenile_cases.ipynb
Labels: enhancement

#75 Milestone 3 - data analysis
  4_data_analysis/4_data_analysis.ipynb
  4_data_analysis/README.md
Labels: documentation, enhancement

#73 Milestone 3- docs(1_datasets): add tbl_RepsAssigned to README
  1_datasets/README.md
Labels: documentation

#77 Modified data analysis
  4_data_analysis/4_data_analysis.ipynb
Labels: enhancement

#70 Milestone 3- docs(collaboration/retrospectives): add Milestone3 retrospectives
  collaboration/retrospectives/3_data_analysis.md
Labels: documentation

#76 main readme update
  README.md
Labels: documentation

#66 Milestone3- 3 eda exploration
  .vscode/settings.json
  3_data_exploration/README.md
  3_data_exploration/notebooks/03_eda_juvenile_cases.ipynb
Labels: help wanted

#78 Milestone 4- Tbl reps assigned re celeaning & 4_data_analysis.ipynb updating
  .gitignore
  2_data_preparation/notebooks/02_clean_core_tables.ipynb
  4_data_analysis/4_data_analysis.ipynb
  4_data_analysis/README.md
Labels: enhancement
